# Troubleshoot Price Feeds

This guide is designed to help you troubleshoot common issues you may encounter when using Pyth Price Feeds.
Follow the steps provided below to diagnose and resolve the issue.




## On-chain Price Feed Issues

### Issue: getPrice() returns `StalePrice()` or `0x19abf40e` error

This error occurs when the price data of the requested asset has not been updated in the last valid time period.
The valid time period for the feed can queried using the [`getValidTime()`](https://github.com/pyth-network/pyth-crosschain/blob/main/target_chains/ethereum/sdk/solidity/AbstractPyth.sol#L22) method.

To resolve this issue: 

- Update the price data by calling [`updatePriceFeeds()`]("https://github.com/pyth-network/pyth-crosschain/blob/main/target_chains/ethereum/sdk/solidity/AbstractPyth.sol#L88") 
by passing the latest updateData from [Hermes](https://hermes.pyth.network/docs/#/rest/latest_vaas).
- Another method to fetch the price is [`getPriceUnsafe()`](https://github.com/pyth-network/pyth-crosschain/blob/main/target_chains/ethereum/sdk/solidity/AbstractPyth.sol#L41)
If the price feed is available, the method will returnt the latest price data with timestamp of last update.
NOTE: This method does not check for stale price data.


### Issue: getPrice() returns `PriceFeedNotFound()` or `0x14aebe68` error

This error occurs when the requested price is not published on the respective chain.
Check the entered [price feed id](https://pyth.network/developers/price-feed-ids) and [pyth-contract address](https://docs.pyth.network/price-feeds/contract-addresses/evm) to make sure they are correct.


### Issue: updatePriceFeeds() returns `InsufficientFee()` or `0x025dbdd4` error

This error occurs when the fee provided for updating the price feed is insufficient. 
Fetch the latest fee by calling `getUpdateFee(bytes[])` method and provide the required fee to `msg.value` when calling `updatePriceFeeds()` method.